###
POST http://localhost:8080/validation/api/items/add
Content-Type: application/json

{
  "itemName": "hello",
  "price": 1000,
  "quantity": 10
}

###
POST http://localhost:8080/validation/api/items/add
Content-Type: application/json

{
  "itemName": "hello",
  "price": "aaa",
  "quantity": 10
}

###
POST http://localhost:8080/validation/api/items/add
Content-Type: application/json

{
  "itemName": "hello",
  "price": 1212,
  "quantity": 10101
}
